version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run: yarn
      - run: yarn pull:wkt
      - run: yarn build
      - run: npx nyc yarn test
      - coveralls/upload
