version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run: yarn
      - run: yarn pull:wkt
      - run: yarn build
      - run: yarn test
      - run: npx nyc report --reporter=text-lcov | npx coveralls
